### ISSUE TITLE
Android JDK8 ERROR for PRE 7.0

### ISSUE THREAD

**Issue by KingAndroid** [rabbitmq/rabbitmq-java-client#311]
````JAVA
io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: com.rabbitmq.client.impl.AMQChannel$$Lambda$0
                                                                            at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:64)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.NoClassDefFoundError: com.rabbitmq.client.impl.AMQChannel$$Lambda$0
                                                                            at com.rabbitmq.client.impl.AMQChannel.enqueueRpc(AMQChannel.java:204)
                                                                            at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:289)
                                                                            at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
                                                                            at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
                                                                            at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:944)
                                                                            at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:903)
                                                                            at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:861)
                                                                            at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1013)`

**Comment by KingAndroid** [comment]
I am using 5.0.0
it works on android 7.0 and over, but not work pre android 7.0

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Same as #310: it’s not enough to compile this client on JDK 8, you must also run on JDK 8 since earlier versions do not implement lambdas. I suspect Android users cannot afford doing that just yet and have to stick to 4.x, which works just fine and will be maintained to the same extent for another few months.

**Comment by michaelklishin** [comment]
Duplicate of #310.

**Comment by michaelklishin** [comment]
The docs were updated to mention that JDK 8 is required *at runtime* the library as well as at compile time. They now mention Android version compatibility for 5.x and 4.x release series as well.
